const Actions = {
  FETCH_ALL_RECIPES: "FETCH_ALL_RECIPES",
  ADD_RECIPE: "ADD_RECIPE",
  UPDATE_RECIPE: "UPDATE_RECIPE",
  DELETE_RECIPE_BY_ID: "DELETE_RECIPE_BY_ID",
} as const;

export { Actions };
