const Mutations = {
  ADD_RECIPE: "ADD_RECIPE",
  UPDATE_RECIPE: "UPDATE_RECIPE",
  DELETE_RECIPE_BY_ID: "DELETE_RECIPE_BY_ID",
  SET_DATA_STATUS: "SET_DATA_STATUS",
  SET_RECIPES: "SET_RECIPES",
  SET_ERROR: "SET_ERROR",
} as const;

export { Mutations };
